docs: change README
danieljancar/soccer-fields pull request #3
Opened 2024-06-14 12:45 UTC by xyuuyaa

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Changed the README. Add short description of program, Add features of program

2024-06-14 13:15 UTC, danieljancar requested changes
Looks alright as a starting point to work on the weekend. Some small changes needed tho 🙈

2024-06-14 13:15 UTC, danieljancar commented on README.md
> +Here’s a more neutral version of the README text:
remove

2024-06-14 13:15 UTC, danieljancar commented on README.md
> +This program is based on the M426 module "Git and Scrum" at BBZW Sursee.
This webapp is ba....

2024-06-14 13:15 UTC, danieljancar commented on README.md
> +This program contains fictional match results of European leagues for the 2023/2024 season. It calculates and displays results in a tabular format for each league.
This webapp contains...

2024-06-15 12:48 UTC, KLGamet commented on README.md
> +Here’s a more neutral version of the README text:
Contents of the readme.md have already been updated in the branch "testing"

2024-06-16 15:26 UTC, closed without merging